name: Check PR Review (Step 1)

# This workflow runs on pull_request_review but only saves data
# It has limited permissions for fork PRs, so it can't label
# The second workflow (label-pr-action.yml) will do the actual labeling

permissions:
  contents: read

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REVIEW_STATE=${{ github.event.review.state }}" >> $GITHUB_ENV
          echo "Workflow triggered for PR #${{ github.event.pull_request.number }}"
          echo "Review state: ${{ github.event.review.state }}"
