name: Label PR After Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals and label
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Count total approvals (any reviewer)
            const approvals = reviews.filter(r => r.state === 'APPROVED').length;

            // Check if the repository owner specifically approved
            const ownerApproved = reviews.some(r => r.state === 'APPROVED' && r.user && r.user.login === context.repo.owner);

            // Collect labels to add (avoid multiple API calls)
            const labelsToAdd = [];
            if (approvals >= 2) labelsToAdd.push('external:approved');
            if (ownerApproved) labelsToAdd.push('owner:approved');

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd
              });
            }