name: PR Review Trigger

# This workflow triggers on reviews but has NO write permissions for fork PRs
# It just completes successfully so workflow_run can pick it up
permissions:
  contents: read

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Log review event
        run: |
          echo "Review submitted on PR #${{ github.event.pull_request.number }}"
          echo "Review state: ${{ github.event.review.state }}"
          echo "Reviewer: ${{ github.event.review.user.login }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR Head Ref: ${{ github.event.pull_request.head.ref }}"
